---
abstract: 'Multipurpose scenarios framework'
author:
  - 'L<Aleksei Melezhik|mailto:melezhik@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.18'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Outthentic
no_index:
  directory:
    - bash_lib
    - examples
    - inc
    - python_lib
    - ruby_lib
    - t
requires:
  Capture::Tiny: '0.30'
  Config::General: 0
  File::ShareDir: 0
  File::Temp: 0
  Hash::Merge: 0
  JSON: 0
  Outthentic::DSL: 0.2.8
  Term::ANSIColor: '4.02'
  YAML: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/melezhik/outthentic
version: 0.3.7
